name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: '0 2 * * *'

env:
  CARGO_INCREMENTAL: 0
  CARGO_NET_RETRY: 10
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1
  RUSTDOCFLAGS: -D warnings
  RUSTFLAGS: -D warnings
  RUSTUP_MAX_RETRIES: 10

defaults:
  run:
    shell: bash

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy,rustfmt
      - name: Install cargo-hack
        uses: taiki-e/install-action@cargo-hack
      - run: cargo fmt --all --check
      - run: cargo clippy --workspace --all-features --all-targets
      - run: cargo hack build --workspace --ignore-private --feature-powerset
      - run: cargo test --workspace --all-features
      - run: cargo doc --workspace --all-features

  spell-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npx cspell --no-progress $(git ls-files)
      - name: Check duplications in dictionary
        run: |
          dup=$(sed '/^$/d' .github/.cspell/dictionary.txt | LC_ALL=C sort -f | uniq -d -i)
          if [[ -n "${dup}" ]]; then
              echo "error: duplicated words in .github/.cspell/dictionary.txt"
              echo "======================================="
              echo "${dup}"
              echo "======================================="
              exit 1
          fi
